goog.addDependency("../../../../script/app.js", ['Mavelous.App'], ['Mavelous.AppRouter', 'Mavelous.BatteryButton', 'Mavelous.CommStatusButtonView', 'Mavelous.CommStatusPopoverViewDelegate', 'Mavelous.CommStatusModel', 'Mavelous.CommandLongModel', 'Mavelous.FlightModeButtonView', 'Mavelous.FlightModePopoverViewDelegate', 'Mavelous.FlightModeModel', 'Mavelous.GpsButtonView', 'Mavelous.GpsPopoverViewDelegate', 'Mavelous.GuideAltitudeView', 'Mavelous.GuideModel', 'Mavelous.LeafletDroneIconModel', 'Mavelous.LeafletPanControlView', 'Mavelous.LeafletPanModel', 'Mavelous.LeafletProviders', 'Mavelous.LeafletView', 'Mavelous.MavlinkAPI', 'Mavelous.ModeStringView', 'Mavelous.PFD', 'Mavelous.PFDSettingsModel', 'Mavelous.PFDView', 'Mavelous.PacketLossModel', 'Mavelous.PopoverView', 'Mavelous.RadioButtonPopoverView', 'Mavelous.SettingsView', 'Mavelous.StatustextView', 'Mavelous.VehicleLeafletPosition', 'goog.Uri', 'goog.array', 'goog.async.AnimationDelay', 'goog.async.Throttle', 'goog.debug.Console', 'goog.debug.FpsDisplay', 'goog.dom', 'goog.net.jsloader']);
goog.addDependency("../../../../script/batterystatus.js", ['Mavelous.BatteryButton'], []);
goog.addDependency("../../../../script/commstatus.js", ['Mavelous.CommStatusButtonView', 'Mavelous.CommStatusModel', 'Mavelous.PacketLossModel'], []);
goog.addDependency("../../../../script/commstatuspopover.js", ['Mavelous.CommStatusPopoverViewDelegate'], []);
goog.addDependency("../../../../script/fakemavlinkapi.js", ['Mavelous.FakeVehicle'], ['goog.math']);
goog.addDependency("../../../../script/flightmode.js", ['Mavelous.CommandLongModel', 'Mavelous.FlightModeButtonView', 'Mavelous.FlightModeModel'], ['Mavelous.util', 'goog.json']);
goog.addDependency("../../../../script/flightmodepopover.js", ['Mavelous.FlightModePopoverViewDelegate'], []);
goog.addDependency("../../../../script/gen-js/Calculator.js", [], []);
goog.addDependency("../../../../script/gen-js/SharedService.js", [], []);
goog.addDependency("../../../../script/gen-js/shared_types.js", [], []);
goog.addDependency("../../../../script/gen-js/tutorial_types.js", [], []);
goog.addDependency("../../../../script/gpsstatus.js", ['Mavelous.GpsButtonView', 'Mavelous.GpsTextView'], []);
goog.addDependency("../../../../script/gpsstatuspopover.js", ['Mavelous.GpsPopoverViewDelegate'], []);
goog.addDependency("../../../../script/guidemodel.js", ['Mavelous.GuideModel'], ['goog.json']);
goog.addDependency("../../../../script/guideview.js", ['Mavelous.GuideAltitudeView'], []);
goog.addDependency("../../../../script/js/thrift.js", [], []);
goog.addDependency("../../../../script/leaflet_app.js", [], ['Mavelous.LeafletDroneIconModel', 'Mavelous.MavlinkAPI']);
goog.addDependency("../../../../script/leafletdroneicon.js", ['Mavelous.LeafletDroneIconModel'], []);
goog.addDependency("../../../../script/leafletpanmodel.js", ['Mavelous.LeafletPanControlView', 'Mavelous.LeafletPanModel'], []);
goog.addDependency("../../../../script/leafletproviders.js", ['Mavelous.LeafletProviders'], []);
goog.addDependency("../../../../script/leafletview.js", ['Mavelous.LeafletView'], []);
goog.addDependency("../../../../script/mavelous-deps.js", [], []);
goog.addDependency("../../../../script/mavlinkapi.js", ['Mavelous.MavlinkAPI', 'Mavelous.MavlinkMessage'], ['Mavelous.FakeVehicle', 'goog.debug.Logger']);
goog.addDependency("../../../../script/mavutil.js", ['Mavelous.util'], ['goog.object']);
goog.addDependency("../../../../script/mission.js", ['mavelous', 'mavelous.Mission', 'mavelous.MissionItem', 'mavelous.MissionItemType'], ['goog.array', 'goog.asserts', 'goog.object']);
goog.addDependency("../../../../script/missionui.js", ['mavelous.ui', 'mavelous.ui.Input', 'mavelous.ui.Label', 'mavelous.ui.Mission', 'mavelous.ui.MissionItemRenderer', 'mavelous.ui.MissionRenderer'], ['goog.dom', 'goog.events', 'goog.events.Event', 'goog.ui.BidiInput', 'goog.ui.Checkbox', 'goog.ui.Checkbox.State', 'goog.ui.Container', 'goog.ui.ContainerRenderer', 'goog.ui.Control', 'goog.ui.ControlRenderer', 'goog.ui.FlatMenuButtonRenderer', 'goog.ui.Select', 'goog.ui.registry', 'mavelous.Mission', 'mavelous.MissionItem', 'mavelous.MissionItemType']);
goog.addDependency("../../../../script/modestringview.js", ['Mavelous.ModeStringView'], ['Mavelous.util']);
goog.addDependency("../../../../script/pfd.js", ['Mavelous.ArtificialHorizon', 'Mavelous.PFD', 'Mavelous.Tape'], ['goog.dom']);
goog.addDependency("../../../../script/pfdsettings.js", ['Mavelous.PFDSettingsModel'], ['goog.json']);
goog.addDependency("../../../../script/pfdview.js", ['Mavelous.PFDView'], ['Mavelous.PFD', 'Mavelous.PFDSettingsModel']);
goog.addDependency("../../../../script/popoverview.js", ['Mavelous.PopoverView', 'Mavelous.SelectionModel'], []);
goog.addDependency("../../../../script/radiopopovers.js", ['Mavelous.RadioButtonPopoverView'], []);
goog.addDependency("../../../../script/router.js", ['Mavelous.AppRouter'], []);
goog.addDependency("../../../../script/settingsview.js", ['Mavelous.SettingsView'], ['Mavelous.PFDSettingsModel']);
goog.addDependency("../../../../script/statustextview.js", ['Mavelous.StatustextView'], []);
goog.addDependency("../../../../script/vehicleleafletposition.js", ['Mavelous.VehicleLeafletPosition'], []);
// This file was autogenerated by calcdeps.py
